services:
  - type: web
    name: fine-tuning-labs-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false